name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.6.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.7.15
  cupertino_icons: ^1.0.6
  
  camera: any
  path: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider: ^2.0.11
  path: ^1.8.2
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true