name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.6.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.7.15
  cupertino_icons: ^1.0.6
  camera: any
  path: any
  path_provider: any
  csv: ^5.0.0
  http: ^1.2.1
  flutter_webview_plugin: ^0.4.0
  flutter_secure_storage: ^5.0.2
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider: ^2.0.11
  path: ^1.8.2
  flutter_lints: ^4.0.0

flutter:
  #assets:
  #  -assets/
  uses-material-design: true
