name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.6.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.7.15
  cupertino_icons: ^1.0.6
  camera: ^0.9.4+5
  path_provider: ^2.0.3
  path: ^1.8.0
  csv: ^5.0.0
  http: ^0.13.6
  flutter_webview_plugin: ^0.4.0
  flutter_secure_storage: ^5.0.2
  url_launcher: ^6.0.9
  image_picker: ^0.8.4+4
  googleapis: ^7.0.0
  googleapis_auth: ^1.0.0
  image: ^4.2.0
  flutter_dotenv: ^5.0.2
  image_cropper: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/downloaded_images/base3-1.png