// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvCeZftZDI7iQbg9QfMfE7obQ8SDKVZOA',
    appId: '1:260354219297:web:bb815d97fd045bb628f260',
    messagingSenderId: '260354219297',
    projectId: 'tcgdex-2b2e5',
    authDomain: 'tcgdex-2b2e5.firebaseapp.com',
    storageBucket: 'tcgdex-2b2e5.appspot.com',
    measurementId: 'G-WR8XQY1R1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY-gnxle16LT_0jJ__2b3dAemM6gY1GwE',
    appId: '1:260354219297:android:8c95b4d10b17902728f260',
    messagingSenderId: '260354219297',
    projectId: 'tcgdex-2b2e5',
    storageBucket: 'tcgdex-2b2e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7BtqBeoJN6NZ5Wmxthyea87fZGcfLcDM',
    appId: '1:260354219297:ios:ab4b81f4f2e7a26528f260',
    messagingSenderId: '260354219297',
    projectId: 'tcgdex-2b2e5',
    storageBucket: 'tcgdex-2b2e5.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7BtqBeoJN6NZ5Wmxthyea87fZGcfLcDM',
    appId: '1:260354219297:ios:ab4b81f4f2e7a26528f260',
    messagingSenderId: '260354219297',
    projectId: 'tcgdex-2b2e5',
    storageBucket: 'tcgdex-2b2e5.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvCeZftZDI7iQbg9QfMfE7obQ8SDKVZOA',
    appId: '1:260354219297:web:212724124506c16128f260',
    messagingSenderId: '260354219297',
    projectId: 'tcgdex-2b2e5',
    authDomain: 'tcgdex-2b2e5.firebaseapp.com',
    storageBucket: 'tcgdex-2b2e5.appspot.com',
    measurementId: 'G-QMJB1F5XVL',
  );

}